# Generated by Django 4.2.2 on 2023-07-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_sal_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('Password', models.IntegerField()),
            ],
        ),
    ]
